### ISSUE TITLE
setup Astro related config files

### ISSUE THREAD

**Issue by takimotok** [takimotok/takimotok.github.io#10]
## TODO

- [ ] astro.config.mjs
- [ ] src/consts.ts
- [ ] src/env.d.ts
- [ ] src/functions.ts
- [ ] tailwind.config.cjs
- [ ] tsconfig.json

## Think later

- [ ] how to handle env. variables on Astro and `src/consts.ts`
